# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

time_zone: Europe/Paris

# values of custom fields (defined in src/settings.yml)
custom_fields:
  {}

# override variables
variables:
  IDX_0: {"state":"86.4","attributes":{"unit_of_measurement":"%","device_class":"humidity","friendly_name":"Room"}}
  IDX_1: {"state":"19.2","attributes":{"unit_of_measurement":"°C","device_class":"temperature","friendly_name":"Room"}}
  IDX_2: {"state":"120","attributes":{"unit_of_measurement":"W","device_class":"power","friendly_name":"Computer"}}
  IDX_3: {"state":"233","attributes":{"unit_of_measurement":"ppm","device_class":"pm25","friendly_name":"Air quality"}}
